var annotated_dup =
[
    [ "doctest", "namespacedoctest.html", [
      [ "detail", "namespacedoctest_1_1detail.html", [
        [ "has_insertion_operator_impl", "namespacedoctest_1_1detail_1_1has__insertion__operator__impl.html", [
          [ "check", "structdoctest_1_1detail_1_1has__insertion__operator__impl_1_1check.html", null ],
          [ "check< T, decltype(os()<< val< T >(), void())>", "structdoctest_1_1detail_1_1has__insertion__operator__impl_1_1check_3_01_t_00_01decltype_07os_07_8d91d0ae55ab2b557e111ab3ba9c02da.html", null ]
        ] ],
        [ "enable_if", "structdoctest_1_1detail_1_1enable__if.html", null ],
        [ "enable_if< true, TYPE >", "structdoctest_1_1detail_1_1enable__if_3_01true_00_01_t_y_p_e_01_4.html", "structdoctest_1_1detail_1_1enable__if_3_01true_00_01_t_y_p_e_01_4" ],
        [ "remove_reference", "structdoctest_1_1detail_1_1remove__reference.html", "structdoctest_1_1detail_1_1remove__reference" ],
        [ "remove_reference< T & >", "structdoctest_1_1detail_1_1remove__reference_3_01_t_01_6_01_4.html", "structdoctest_1_1detail_1_1remove__reference_3_01_t_01_6_01_4" ],
        [ "remove_reference< T && >", "structdoctest_1_1detail_1_1remove__reference_3_01_t_01_6_6_01_4.html", "structdoctest_1_1detail_1_1remove__reference_3_01_t_01_6_6_01_4" ],
        [ "is_lvalue_reference", "structdoctest_1_1detail_1_1is__lvalue__reference.html", null ],
        [ "is_lvalue_reference< T & >", "structdoctest_1_1detail_1_1is__lvalue__reference_3_01_t_01_6_01_4.html", null ],
        [ "remove_const", "structdoctest_1_1detail_1_1remove__const.html", "structdoctest_1_1detail_1_1remove__const" ],
        [ "remove_const< const T >", "structdoctest_1_1detail_1_1remove__const_3_01const_01_t_01_4.html", "structdoctest_1_1detail_1_1remove__const_3_01const_01_t_01_4" ],
        [ "is_enum", "structdoctest_1_1detail_1_1is__enum.html", null ],
        [ "underlying_type", "structdoctest_1_1detail_1_1underlying__type.html", "structdoctest_1_1detail_1_1underlying__type" ],
        [ "deferred_false", "structdoctest_1_1detail_1_1deferred__false.html", null ],
        [ "StringMakerBase", "structdoctest_1_1detail_1_1_string_maker_base.html", null ],
        [ "StringMakerBase< true >", "structdoctest_1_1detail_1_1_string_maker_base_3_01true_01_4.html", null ],
        [ "TestFailureException", "structdoctest_1_1detail_1_1_test_failure_exception.html", null ],
        [ "Subcase", "structdoctest_1_1detail_1_1_subcase.html", "structdoctest_1_1detail_1_1_subcase" ],
        [ "Result", "structdoctest_1_1detail_1_1_result.html", "structdoctest_1_1detail_1_1_result" ],
        [ "ExpressionDecomposer", "structdoctest_1_1detail_1_1_expression_decomposer.html", "structdoctest_1_1detail_1_1_expression_decomposer" ],
        [ "TestSuite", "structdoctest_1_1detail_1_1_test_suite.html", "structdoctest_1_1detail_1_1_test_suite" ],
        [ "TestCase", "structdoctest_1_1detail_1_1_test_case.html", "structdoctest_1_1detail_1_1_test_case" ],
        [ "RelationalComparator", "structdoctest_1_1detail_1_1_relational_comparator.html", "structdoctest_1_1detail_1_1_relational_comparator" ],
        [ "ResultBuilder", "structdoctest_1_1detail_1_1_result_builder.html", "structdoctest_1_1detail_1_1_result_builder" ],
        [ "IExceptionTranslator", "structdoctest_1_1detail_1_1_i_exception_translator.html", "structdoctest_1_1detail_1_1_i_exception_translator" ],
        [ "ExceptionTranslator", "classdoctest_1_1detail_1_1_exception_translator.html", "classdoctest_1_1detail_1_1_exception_translator" ],
        [ "StringStreamBase", "structdoctest_1_1detail_1_1_string_stream_base.html", null ],
        [ "StringStreamBase< true >", "structdoctest_1_1detail_1_1_string_stream_base_3_01true_01_4.html", null ],
        [ "StringStream", "structdoctest_1_1detail_1_1_string_stream.html", null ],
        [ "ContextScopeBase", "classdoctest_1_1detail_1_1_context_scope_base.html", "classdoctest_1_1detail_1_1_context_scope_base" ],
        [ "ContextScope", "classdoctest_1_1detail_1_1_context_scope.html", "classdoctest_1_1detail_1_1_context_scope" ],
        [ "MessageBuilder", "structdoctest_1_1detail_1_1_message_builder.html", "structdoctest_1_1detail_1_1_message_builder" ]
      ] ],
      [ "String", "classdoctest_1_1_string.html", "classdoctest_1_1_string" ],
      [ "TestCaseData", "structdoctest_1_1_test_case_data.html", "structdoctest_1_1_test_case_data" ],
      [ "AssertData", "structdoctest_1_1_assert_data.html", "structdoctest_1_1_assert_data" ],
      [ "MessageData", "structdoctest_1_1_message_data.html", "structdoctest_1_1_message_data" ],
      [ "SubcaseSignature", "structdoctest_1_1_subcase_signature.html", "structdoctest_1_1_subcase_signature" ],
      [ "IContextScope", "structdoctest_1_1_i_context_scope.html", "structdoctest_1_1_i_context_scope" ],
      [ "ContextOptions", "structdoctest_1_1_context_options.html", "structdoctest_1_1_context_options" ],
      [ "StringMaker", "structdoctest_1_1_string_maker.html", null ],
      [ "StringMaker< T * >", "structdoctest_1_1_string_maker_3_01_t_01_5_01_4.html", null ],
      [ "StringMaker< R C::* >", "structdoctest_1_1_string_maker_3_01_r_01_c_1_1_5_01_4.html", null ],
      [ "Approx", "classdoctest_1_1_approx.html", "classdoctest_1_1_approx" ],
      [ "Context", "classdoctest_1_1_context.html", "classdoctest_1_1_context" ],
      [ "CurrentTestCaseStats", "structdoctest_1_1_current_test_case_stats.html", "structdoctest_1_1_current_test_case_stats" ],
      [ "TestCaseException", "structdoctest_1_1_test_case_exception.html", "structdoctest_1_1_test_case_exception" ],
      [ "TestRunStats", "structdoctest_1_1_test_run_stats.html", "structdoctest_1_1_test_run_stats" ],
      [ "QueryData", "structdoctest_1_1_query_data.html", "structdoctest_1_1_query_data" ],
      [ "IReporter", "structdoctest_1_1_i_reporter.html", "structdoctest_1_1_i_reporter" ]
    ] ],
    [ "AddPlanetCommand", "class_add_planet_command.html", "class_add_planet_command" ],
    [ "Base", "class_base.html", "class_base" ],
    [ "basic_ostream", "classbasic__ostream.html", null ],
    [ "char_traits", "structchar__traits.html", null ],
    [ "CloseCommand", "class_close_command.html", "class_close_command" ],
    [ "Command", "class_command.html", "class_command" ],
    [ "CommandController", "class_command_controller.html", "class_command_controller" ],
    [ "CreateJediCommand", "class_create_jedi_command.html", "class_create_jedi_command" ],
    [ "DemoteJediCommand", "class_demote_jedi_command.html", "class_demote_jedi_command" ],
    [ "ExitCommand", "class_exit_command.html", "class_exit_command" ],
    [ "Galaxy", "class_galaxy.html", "class_galaxy" ],
    [ "GalaxyManager", "class_galaxy_manager.html", "class_galaxy_manager" ],
    [ "GetMostUsedSaberColorCommand", "class_get_most_used_saber_color_command.html", "class_get_most_used_saber_color_command" ],
    [ "GetStrongestJediCommand", "class_get_strongest_jedi_command.html", "class_get_strongest_jedi_command" ],
    [ "GetYoungestJediCommand", "class_get_youngest_jedi_command.html", "class_get_youngest_jedi_command" ],
    [ "HelpCommand", "class_help_command.html", "class_help_command" ],
    [ "Jedi", "class_jedi.html", "class_jedi" ],
    [ "OpenCommand", "class_open_command.html", "class_open_command" ],
    [ "OperatorPlusCommand", "class_operator_plus_command.html", "class_operator_plus_command" ],
    [ "Planet", "class_planet.html", "class_planet" ],
    [ "PrintCommand", "class_print_command.html", "class_print_command" ],
    [ "PromoteJediCommand", "class_promote_jedi_command.html", "class_promote_jedi_command" ],
    [ "RemoveCommand", "class_remove_command.html", "class_remove_command" ],
    [ "SaveAsCommand", "class_save_as_command.html", "class_save_as_command" ],
    [ "SaveCommand", "class_save_command.html", "class_save_command" ],
    [ "String", "class_string.html", "class_string" ],
    [ "tuple", "classtuple.html", null ],
    [ "Unite", "class_unite.html", "class_unite" ],
    [ "Vector", "class_vector.html", "class_vector" ]
];