var annotated_dup =
[
    [ "AddPlanetCommand", "class_add_planet_command.html", "class_add_planet_command" ],
    [ "Base", "class_base.html", "class_base" ],
    [ "CloseCommand", "class_close_command.html", "class_close_command" ],
    [ "Command", "class_command.html", "class_command" ],
    [ "CommandController", "class_command_controller.html", "class_command_controller" ],
    [ "CreateJediCommand", "class_create_jedi_command.html", "class_create_jedi_command" ],
    [ "DemoteJediCommand", "class_demote_jedi_command.html", "class_demote_jedi_command" ],
    [ "ExitCommand", "class_exit_command.html", "class_exit_command" ],
    [ "Galaxy", "class_galaxy.html", "class_galaxy" ],
    [ "GalaxyManager", "class_galaxy_manager.html", "class_galaxy_manager" ],
    [ "GetMostUsedSaberColorCommand", "class_get_most_used_saber_color_command.html", "class_get_most_used_saber_color_command" ],
    [ "GetStrongestJediCommand", "class_get_strongest_jedi_command.html", "class_get_strongest_jedi_command" ],
    [ "GetYoungestJediCommand", "class_get_youngest_jedi_command.html", "class_get_youngest_jedi_command" ],
    [ "HelpCommand", "class_help_command.html", "class_help_command" ],
    [ "IFactory", "class_i_factory.html", null ],
    [ "Jedi", "class_jedi.html", "class_jedi" ],
    [ "OpenCommand", "class_open_command.html", "class_open_command" ],
    [ "OperatorPlusCommand", "class_operator_plus_command.html", "class_operator_plus_command" ],
    [ "Planet", "class_planet.html", "class_planet" ],
    [ "PrintCommand", "class_print_command.html", "class_print_command" ],
    [ "PromoteJediCommand", "class_promote_jedi_command.html", "class_promote_jedi_command" ],
    [ "RemoveCommand", "class_remove_command.html", "class_remove_command" ],
    [ "SaveAsCommand", "class_save_as_command.html", "class_save_as_command" ],
    [ "SaveCommand", "class_save_command.html", "class_save_command" ],
    [ "String", "class_string.html", "class_string" ],
    [ "Vector", "class_vector.html", "class_vector" ]
];